// Postinstall helper. Ensures Noto Sans Tamil is embedded as a base64 TS
// constant at convex/_assets/notoSansTamil.ts so the PDF renderer can draw
// Tamil concept-name footnotes + student names. We base64-embed (rather
// than ship a .ttf file in convex/) because Convex's bundler does not
// reliably include non-source-code assets; embedding bytes in a .ts
// constant guarantees they reach the cloud runtime.
//
// Idempotent: skips if the target module is already present + plausibly
// sized. Safe to run repeatedly; postinstall invokes it after every
// `npm install`.
//
// Note: this file previously also fetched sharp's linux-arm64 binaries,
// but Phase E pivoted to a pure-JS PDF-native clipping technique that
// doesn't need sharp. The font is the only remaining bundled asset.

import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "..");

// Noto Sans Tamil variable TTF from the canonical Google Fonts repo.
// ~330KB raw. pdf-lib + fontkit handle variable fonts — when embedded
// without an axis spec, the default instance (wdth=100, wght=400) is used.
const FONT_URL =
  "https://raw.githubusercontent.com/google/fonts/main/ofl/notosanstamil/NotoSansTamil%5Bwdth%2Cwght%5D.ttf";

const FONT_TS_PATH = path.join(
  REPO,
  "convex",
  "_assets",
  "notoSansTamil.ts",
);

function fetchBuffer(url, redirects = 0) {
  return new Promise((resolve, reject) => {
    if (redirects > 5) {
      reject(new Error("Too many redirects"));
      return;
    }
    https
      .get(url, (res) => {
        if (res.statusCode === 301 || res.statusCode === 302) {
          fetchBuffer(res.headers.location, redirects + 1).then(
            resolve,
            reject,
          );
          return;
        }
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} fetching ${url}`));
          return;
        }
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks)));
        res.on("error", reject);
      })
      .on("error", reject);
  });
}

async function installFont() {
  if (fs.existsSync(FONT_TS_PATH)) {
    // Treat anything >200KB as a real install (raw is 330KB, base64 is
    // ~440KB plus boilerplate — comfortably above the threshold).
    const stat = fs.statSync(FONT_TS_PATH);
    if (stat.size > 200_000) {
      console.log(`[install-fonts] Tamil font module present — skipping`);
      return;
    }
  }
  console.log(`[install-fonts] fetching ${FONT_URL}`);
  const ttf = await fetchBuffer(FONT_URL);
  if (ttf.length < 50_000) {
    throw new Error(
      `Tamil font payload is suspiciously small (${ttf.length} bytes)`,
    );
  }
  const b64 = ttf.toString("base64");
  fs.mkdirSync(path.dirname(FONT_TS_PATH), { recursive: true });
  const fileContents =
    `// Auto-generated by scripts/install-fonts.mjs. Do not edit by hand.\n` +
    `// Noto Sans Tamil Regular (Google Fonts / Noto, OFL), base64-encoded so\n` +
    `// Convex actions can load it without runtime fetch.\n` +
    `// Original source: ${FONT_URL}\n` +
    `// Size: ${ttf.length} bytes → ${b64.length} base64 chars\n` +
    `\n` +
    `export const NOTO_SANS_TAMIL_BASE64 = "${b64}";\n`;
  fs.writeFileSync(FONT_TS_PATH, fileContents, "utf8");
  console.log(
    `[install-fonts] wrote ${FONT_TS_PATH} (${ttf.length} bytes raw)`,
  );
}

async function main() {
  try {
    await installFont();
  } catch (e) {
    // Do NOT fail the install. If the dev is offline, the font module may
    // be missing — that's a build error the dev can fix later by re-running
    // this script with network access.
    console.warn(
      `[install-fonts] WARNING: ${String(e)} — continuing. Re-run "node scripts/install-fonts.mjs" when online.`,
    );
  }
}

main();
